packages:
    - packages/*
catalog:
    "@chromatic-com/storybook": "1"
    "@fontsource/open-sans": ^5.0.28
    "@fortawesome/fontawesome-svg-core": ^6.4.2
    "@fortawesome/free-regular-svg-icons": ^6.4.2
    "@fortawesome/free-solid-svg-icons": ^6.4.2
    "@fortawesome/react-fontawesome": ^0.2.0
    "@storybook/addon-essentials": ^8.1.9
    "@storybook/addon-interactions": ^8.1.9
    "@storybook/addon-links": ^8.1.9
    "@storybook/blocks": ^8.1.9
    "@storybook/react": ^8.1.9
    "@storybook/react-vite": ^8.1.9
    "@storybook/test": ^8.1.9
    "@types/css-modules": ^1.0.3
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
    "@typescript-eslint/eslint-plugin": ^5.62.0
    "@typescript-eslint/parser": ^5.62.0
    "@vitejs/plugin-react": ^4.3.1
    eslint: ^8.57.0
    eslint-plugin-react-hooks: ^4.6.2
    eslint-plugin-react-refresh: ^0.3.5
    eslint-plugin-storybook: ^0.8.0
    prettier: 2.8.8
    prop-types: 15.8.1
    react: ^18.3.1
    react-dom: ^18.3.1
    storybook: ^8.1.9
    stylelint: ^15.11.0
    stylelint-config-standard: ^33.0.0
    tsx: ^4.19.2
    typescript: ^5.6.2
    vite: ^4.5.3
