packages:
    - packages/*
catalog:
    "@chromatic-com/storybook": ^3.2.3
    "@eslint/compat": ^1.2.1
    "@eslint/eslintrc": ^3.1.0
    "@eslint/js": ^9.13.0
    "@fontsource/open-sans": ^5.0.28
    "@fortawesome/fontawesome-svg-core": ^6.7.2
    "@fortawesome/free-regular-svg-icons": ^6.7.2
    "@fortawesome/free-solid-svg-icons": ^6.7.2
    "@fortawesome/react-fontawesome": ^0.2.2
    "@storybook/addon-essentials": ^8.4.7
    "@storybook/addon-interactions": ^8.4.7
    "@storybook/addon-links": ^8.4.7
    "@storybook/blocks": ^8.4.7
    "@storybook/react": ^8.4.7
    "@storybook/react-vite": ^8.4.7
    "@storybook/test": ^8.4.7
    "@testing-library/dom": ^10.4.0
    "@testing-library/react": ^16.1.0
    "@testing-library/user-event": ^14.5.2
    "@types/css-modules": ^1.0.3
    "@types/react": ^19.0.2
    "@types/react-dom": ^19.0.2
    "@typescript-eslint/eslint-plugin": ^8.18.1
    "@typescript-eslint/parser": ^8.18.1
    "@vitejs/plugin-react": ^4.3.1
    eslint: ^9.13.0
    eslint-plugin-react-hooks: ^5.1.0
    eslint-plugin-react-refresh: ^0.3.5
    eslint-plugin-storybook: ^0.11.1
    globals: ^15.11.0
    jsdom: ^25.0.1
    prettier: 2.8.8
    prop-types: 15.8.1
    react: ^19.0.0
    react-dom: ^19.0.0
    storybook: ^8.4.7
    stylelint: ^15.11.0
    stylelint-config-standard: ^33.0.0
    tsx: ^4.19.2
    typescript: ^5.6.2
    vite: ^5.4.11
    vitest: ^2.1.8
